theme: jekyll-theme-merlot
    #  <h1><a href="https://wsweber.github.io/">wsweber</a></h1>
     <title>Trocando GitHub Pages | wsweber</title>
     <script type="application/ld+json">
{"headline":"Welcome to GitHub Pages","url":"https://wsweber.github.io/","@type":"WebSite","name":"wsweber","@context":"https://schema.org"}</script>
